### ISSUE TITLE
Hi, 

### ISSUE THREAD

**Issue by monglio** [Rafiot/pdfid#1]
Thank you for making great tools.

I found one problem during the test.

If the file name to be scanned contains the string "[", "]", it is not checked.

For example
C: \ python pdfid.py "c: \[test]abcd.pdf"

Do not scan pdf files ..

I'd like to analyze the code and report directly on the code
It seems to take time because I am a beginner in python.

If I find the problem code, I will write it back.

Thank you.

**Comment by Rafiot** [comment]
I'm not the developer of pdfid, and just did a fork here to keep track of the changes. Also, I'm not a windows user so I have no idea how it is supposed to be done on this platform.

**Comment by monglio** [comment]
oh... sorry
i understand you
have a good time~!
